### Register User
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "test",
  "email": "test4@example.com",
  "password": "test1234",
  "confirmPassword": "test1234"
}

### Login User
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test1234"
}

### Get Current
GET http://localhost:8080/api/users/current
Authorization: dd1a4155-68ce-4c18-864a-a11acd4e7a82

### Login Google
POST http://localhost:8080/api/users/google

### Login Google
POST http://localhost:8080/api/users/google/callback?code=4%2F0AeanS0ZqR8FbA3fRYOvqt1Sifx9YGvT32oIyCcMA5rqChlb42XywDWEGqfm0JIgm8vmTvA&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=1&prompt=none

### Forgot Pass
POST http://localhost:8080/api/users/forgot-password
Content-Type: application/json

{
  "email": "brianashari318@gmail.com"
}

### OTP
POST http://localhost:8080/api/users/validateOtp
Content-Type: application/json

{
  "otp": 6347
}

### Reset Pass
POST http://localhost:8080/api/users/reset-password
Content-Type: application/json

{
  "newPassword": "Test1234*",
  "confirmPassword": "Test1234*"
}

### Change Username
PATCH http://localhost:8080/api/users/current/userId
Content-Type: application/json
Authorization: 3dfff5c4-c295-472f-8c1b-9d97790cbd20

{
  "username": "updateUsername"
}